apiVersion: applicationmonitoring.integreatly.org/v1alpha1
kind: ApplicationMonitoring
metadata:
  name: example-applicationmonitoring
spec:
  labelSelector: "middleware"
  blackboxTargets:
    - http://prometheus.io
