apiVersion: v1
data:
  blackbox.yml: |-
    modules:
      http_2xx:
        prober: http
      http_post_2xx:
        prober: http
        http:
          method: POST
kind: ConfigMap
metadata:
  name: {{ .BlackboxExporterConfigmapName }}
  namespace: {{ .Namespace }}
